data_ingestion:
  test_size: 0.2

feature_engineering:
  max_features: 5000

model_building:
  models:
    GradientBoosting:
      n_estimators: 200
      learning_rate: 0.1
      max_depth: 3
      random_state: 42

    RandomForest:
      n_estimators: 200
      max_depth: 3
      random_state: 42

    LogisticRegression:
      solver: liblinear
      C: 1.0
      max_iter: 200
      random_state: 42

    XGBoost:
      n_estimators: 200
      learning_rate: 0.1
      max_depth: 3
      random_state: 42








